name: CI_prev

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master
  #    - main
  #pull_request:
  
jobs:
  test:
    strategy:
      fail-fast: True
      matrix:
        pg: [16]
        ccflags: ['']
        
    name: test_PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download and build PostgreSQL ${{ matrix.pg }}
      - run: |
          mkdir ~/workdir
          cd ~/workdir
          curl -O https://ftp.postgresql.org/pub/source/v${{ matrix.pg }}.0/postgresql-${{ matrix.pg }}.0.tar.bz2
          tar xjf postgresql-${{ matrix.pg }}.0.tar.bz2
          cd postgresql-${{ matrix.pg }}.0
          ./configure --prefix ~/workdir/db
          make
      - name: confirm directory
      - run: |
          pwd
          ls
      - name: install SQLite
      - run: |
          cd ~/workdir
          wget https://www.sqlite.org/2023/sqlite-src-3420000.zip
          unzip sqlite-src-3420000.zip
          cd sqlite-src-3420000
          ./configure --enable-fts5
          make
          make install
      #- run: docker build -t fdw_test --build-arg PG_MAJOR=${{ matrix.pg }} .
      #- run: docker run --rm fdw_test
      #  env:
      #    CCFLAGS: ${{ matrix.ccflags }}
