name: CI_prev

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master
  #    - main
  #pull_request:
  
jobs:
  test:
    strategy:
      fail-fast: True
      matrix:
        pg: [16]
        ccflags: ['']
        
    name: test_PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install locales
        run: |
          sudo apt-get update
          sudo apt-get install locales language-pack-ja
          sudo locale-gen ja_JP.EUC-JP
          sudo apt-get update
          sudo apt-get install language-pack-ko-base language-pack-ko
          sudo locale-gen ko_KR.EUC-KR
          sudo apt-get update
          sudo apt-get install language-pack-bg-base language-pack-bg
          sudo locale-gen bg_BG
