name: CI_prev

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master
  #    - main
  #pull_request:
  
  
jobs:
  test:
    env:
      SQLITE_VERSION : "342000"
    strategy:
      fail-fast: false
      matrix:
        pg: ["16.0","15.3","14.8","13.11","12.15"]
        
    name: test_PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install locales
        run: bash install_locales.sh
      
      - name: download and build PostgreSQL ${{ matrix.pg }}
        run: bash download_build_postgres.sh ${{ matrix.pg }}
      
      - name: install SQLite
        run: bash install_sqlite.sh ${{ env.SQLITE_VERSION }}
      
      - name: build sqlite_fdw
        run: bash build_sqlite_fdw.sh ${{ matrix.pg }}
      
      - name: execute sqlite_fdw test
        run: bash execute_test.sh ${{ matrix.pg }}
