name: CI_prev

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master
  #    - main
  #pull_request:
  
jobs:
  test:
    strategy:
      fail-fast: True
      matrix:
        pg: [16,15,14,13,12]
        ccflags: ['']
        
    name: test_PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install locales
        run: |
          sudo apt-get update
          sudo apt-get install locales language-pack-ja
          sudo locale-gen ja_JP.EUC-JP
          sudo apt-get update
          sudo apt-get install language-pack-ko-base language-pack-ko
          sudo locale-gen ko_KR.EUC-KR
          sudo apt-get update
          sudo apt-get install language-pack-bg-base language-pack-bg
          sudo locale-gen bg_BG
      - name: download and build PostgreSQL ${{ matrix.pg }}
        run: |
          mkdir ~/workdir
          cd ~/workdir
          curl -O https://ftp.postgresql.org/pub/source/v${{ matrix.pg }}.0/postgresql-${{ matrix.pg }}.0.tar.bz2
          tar xjf postgresql-${{ matrix.pg }}.0.tar.bz2
          cd postgresql-${{ matrix.pg }}.0
          ./configure --prefix ~/workdir/db
          make
      - name: install SQLite
        run: |
          cd ~/workdir
          wget https://www.sqlite.org/2023/sqlite-src-3420000.zip
          unzip sqlite-src-3420000.zip
          pwd
          ls -l
          cd sqlite-src-3420000
          ./configure --enable-fts5
          make
          sudo make install
      - name: build sqlite_fdw
        run: |
          cd ~/workdir/postgresql-16.0/contrib
          git clone https://github.com/pgspider/sqlite_fdw.git
          cd sqlite_fdw
          export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
          make

      - name: execute sqlite_fdw test
        run: |
          cd ~/workdir/postgresql-${{ matrix.pg }}.0/contrib/sqlite_fdw
          ./test.sh
