name: install sqlite

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install sqlite
      run: 
        cd workdir/sqlite-src-3420000
        ls
        pwd
