name: docker test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: docker hello world
      run: |
        ls
        pwd
        docker run hello-world
    - name: docker images 
      run: 
        docker images
