name: CI

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master
  #    - main
  #pull_request:
  
jobs:
  test:
    strategy:
      fail-fast: True
      matrix:
        pg: [16]
        ccflags: ['']
        
    name: PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pwd
          ls
      - run: docker build -t parquet_fdw --build -arg PG_MAJOR=${{ matrix.pg }} .
      - run: docker run --rm parquet_fdw
        env:
          CCFLAGS: ${{ matrix.ccflags }}
