name: install sqlite

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: moving current directory and list segments
      run: 
        cd workdir/sqlite-src-34200000
        ls
    - name: install sqlite
      run: sudo make install
